server:
  port: 8888
spring:
  cloud:
    config:
      server:
        encrypt.enabled: false
        git:
          uri: https://github.com/syarbeats/blog-config/
          searchPaths: gateway, blog
          username: syarbeats
          password: ******
